(ns projecteuler02-v2)

(comment
  Even Fibonacci numbers
  Problem 2
  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
)


(defn fib
  ([] (fib 1 2))
  ([curr next] (cons curr (lazy-seq (fib next (+ curr next)))))
)

(->>
  (fib)
  (take-while #(< % 4.0E6))
  (filter even?)
  (reduce +)
)
